name: Build Android APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Create placeholder app icons
        run: |
          # Install ImageMagick to create placeholder icons
          sudo apt-get update
          sudo apt-get install -y imagemagick
          
          # Create placeholder icon for different densities
          mkdir -p app/src/main/res/mipmap-mdpi
          mkdir -p app/src/main/res/mipmap-hdpi
          mkdir -p app/src/main/res/mipmap-xhdpi
          mkdir -p app/src/main/res/mipmap-xxhdpi
          mkdir -p app/src/main/res/mipmap-xxxhdpi
          
          # Create simple colored icons with "AI" text
          convert -size 48x48 xc:#4CAF50 -gravity center -pointsize 24 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-mdpi/ic_launcher.png
          convert -size 72x72 xc:#4CAF50 -gravity center -pointsize 36 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-hdpi/ic_launcher.png
          convert -size 96x96 xc:#4CAF50 -gravity center -pointsize 48 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-xhdpi/ic_launcher.png
          convert -size 144x144 xc:#4CAF50 -gravity center -pointsize 72 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          convert -size 192x192 xc:#4CAF50 -gravity center -pointsize 96 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          
          # Create round icons
          convert -size 48x48 xc:none -draw "circle 24,24 24,0" -fill '#4CAF50' -draw "circle 24,24 24,0" -gravity center -pointsize 24 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-mdpi/ic_launcher_round.png
          convert -size 72x72 xc:none -draw "circle 36,36 36,0" -fill '#4CAF50' -draw "circle 36,36 36,0" -gravity center -pointsize 36 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-hdpi/ic_launcher_round.png
          convert -size 96x96 xc:none -draw "circle 48,48 48,0" -fill '#4CAF50' -draw "circle 48,48 48,0" -gravity center -pointsize 48 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
          convert -size 144x144 xc:none -draw "circle 72,72 72,0" -fill '#4CAF50' -draw "circle 72,72 72,0" -gravity center -pointsize 72 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
          convert -size 192x192 xc:none -draw "circle 96,96 96,0" -fill '#4CAF50' -draw "circle 96,96 96,0" -gravity center -pointsize 96 -fill white -annotate +0+0 "AI" app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
      
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
